all: generator_example.exe regex_example.exe

regex_example.exe: regex_example.cs
	mcs regex_example.cs

generator_example.exe: generator_example.cs
	mcs generator_example.cs

clean:
	rm regex_example.exe generator_example.exe

